name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests - Ruby ${{ matrix.ruby }}
    strategy: { matrix: { ruby: [3.2, 3.3, 3.4, 3.5] } }

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup test database
        run: cd test/dummy && bundle exec rake db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundle exec rake test
  lint:
    runs-on: ubuntu-latest
    name: Lint - StandardRB
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: bundle install
        run: bundle install
      - name: bundle exec standardrb
        run: bundle exec standardrb
  security:
    runs-on: ubuntu-latest
    name: Security - Brakeman (Rails ${{ matrix.rails }})
    strategy:
      matrix:
        rails: ["~> 8.0.0", "~> 8.1.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: bundle install
        run: bundle install
      - name: Run Brakeman vendor scan
        run: RAILS_VERSION="${{ matrix.rails }}" bundle exec rake brakeman:vendor_scan
